const state = { batches: [], settings: { defaultF1: 7, defaultF2: 2 }, deferredPrompt: null };
const faces = ['😖','😕','😐','🙂','🤩'];
const $ = id => document.getElementById(id);
function apiUrl(params){const base=window.KOMBUCHA_CONFIG?.API_URL||'';if(!base||base.includes('PASTE_YOUR'))throw new Error('URL Apps Script non configurée dans config.js.');return `${base}?${new URLSearchParams(params)}`;}
function jsonp(params){return new Promise((resolve,reject)=>{const cb=`kb_${Date.now()}_${Math.floor(Math.random()*10000)}`,s=document.createElement('script');const t=setTimeout(()=>{cleanup();reject(new Error('Le serveur ne répond pas.'));},20000);function cleanup(){clearTimeout(t);delete window[cb];s.remove()}window[cb]=d=>{cleanup();resolve(d)};s.onerror=()=>{cleanup();reject(new Error('Erreur de communication avec Google Apps Script.'))};params.callback=cb;s.src=apiUrl(params);document.head.appendChild(s)})}
async function api(action,payload={}){const response=await jsonp({action,payload:encodeURIComponent(JSON.stringify(payload))});if(!response?.ok)throw new Error(response?.error||'Erreur inconnue');return response.data}
function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2800)}
function banner(t,k='info'){const e=$('connectionBanner');e.textContent=t;e.className=`banner ${k}`}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmt(iso){return iso?new Date(iso).toLocaleString('fr-FR',{dateStyle:'medium',timeStyle:'short'}):'—'}
function duration(ms){if(ms<=0)return 'Terminé';const d=Math.floor(ms/86400000),h=Math.floor(ms/3600000)%24,m=Math.floor(ms/60000)%60;return `${d}j ${String(h).padStart(2,'0')}h ${String(m).padStart(2,'0')}m`}
function dataFor(b){return b.phase==='F2'?{start:b.f2StartAt,end:b.f2EndAt,days:b.f2Days}:{start:b.f1StartAt,end:b.f1EndAt,days:b.f1Days}}
function card(b,done){const d=dataFor(b),rating=Number(b.rating||0);const details=`<div class="details"><div class="detail"><small>Litres</small><strong>${esc(b.liters??'—')} L</strong></div><div class="detail"><small>Thé</small><strong>${esc(b.teaGrams??'—')} g</strong></div><div class="detail"><small>Sucre</small><strong>${esc(b.sugarGrams??'—')} g</strong></div><div class="detail"><small>Durée ${esc(b.phase)}</small><strong>${esc(d.days)} j</strong></div><div class="detail"><small>Démarrée</small><strong>${esc(fmt(d.start))}</strong></div><div class="detail"><small>Fin prévue</small><strong>${esc(fmt(d.end))}</strong></div></div>`;
const actions=done?'':`<div class="card-actions">${b.phase==='F1'?`<button class="secondary-action" data-action="f2" data-id="${esc(b.id)}">Passer en F2</button>`:''}<button class="primary-btn" data-action="edit" data-id="${esc(b.id)}">Modifier</button></div>`;
const ratingHtml=done?`<div class="rating-row"><span class="meta">Votre note</span><div class="rating-buttons">${faces.map((f,i)=>`<button class="rating-btn ${rating===i+1?'selected':''}" data-action="rate" data-rating="${i+1}" data-id="${esc(b.id)}">${f}</button>`).join('')}</div></div>`:'';
return `<article class="batch-card"><div class="card-top"><div><p class="card-name">${esc(b.name)}</p><div class="meta">Créé le ${esc(fmt(b.createdAt))}</div></div><span class="badge ${done?'done':b.phase.toLowerCase()}">${done?'Terminé':b.phase}</span></div><div class="countdown"><div class="count-label">${done?'FERMENTATION TERMINÉE':`COMPTE À REBOURS · ${b.phase}`}</div><div class="timer ${done?'done':''}" data-end="${esc(d.end)}">${done?'Terminé':duration(new Date(d.end)-Date.now())}</div>${done?'':`<div class="progress"><i data-start="${esc(d.start)}" data-end="${esc(d.end)}"></i></div>`}</div>${b.phase==='F2'&&b.flavor?`<p class="card-note"><strong>Parfum :</strong> ${esc(b.flavor)}</p>`:''}${b.f1Notes?`<p class="card-note">${esc(b.phase==='F1'?b.f1Notes:b.f1Notes)}</p>`:''}${b.f2Notes?`<p class="card-note">${esc(b.f2Notes)}</p>`:''}${details}${actions}${ratingHtml}</article>`}
function render(){const active=state.batches.filter(b=>b.status!=='COMPLETED');const completed=state.batches.filter(b=>b.status==='COMPLETED').sort((a,b)=>new Date(b.completedAt||b.f2EndAt)-new Date(a.completedAt||a.f2EndAt));$('activeList').innerHTML=active.length?active.map(b=>card(b,false)).join(''):$('emptyTemplate').innerHTML;$('completedList').innerHTML=completed.length?completed.map(b=>card(b,true)).join(''):`<div class="empty-state"><div class="empty-icon">🌿</div><strong>Pas encore d’historique</strong><span>Les batchs terminés apparaîtront ici.</span></div>`;}
function ticks(){document.querySelectorAll('.timer[data-end]').forEach(e=>{const diff=new Date(e.dataset.end)-Date.now();if(diff<=0){e.textContent='Terminé';e.classList.add('done');loadData(true).catch(()=>{})}else e.textContent=duration(diff)});document.querySelectorAll('.progress i').forEach(e=>{const s=new Date(e.dataset.start).getTime(),end=new Date(e.dataset.end).getTime();e.style.width=`${Math.min(100,Math.max(0,(Date.now()-s)/(end-s)*100))}%`})}
async function loadData(silent=false){try{const d=await api('list');state.batches=d.batches||[];state.settings=d.settings||state.settings;$('defaultF1').value=state.settings.defaultF1;$('defaultF2').value=state.settings.defaultF2;render();ticks();banner(`${state.batches.length} batch${state.batches.length>1?'s':''} synchronisé${state.batches.length>1?'s':''}.`,'ok')}catch(e){banner(e.message,'error');if(!silent)toast(e.message);throw e}}
function page(name){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active-page'));$(`page-${name}`).classList.add('active-page');document.querySelectorAll('.nav-btn').forEach(n=>n.classList.toggle('active',n.dataset.page===name))}
function show(id){$(id).classList.remove('hidden');$(id).setAttribute('aria-hidden','false')};function hide(id){$(id).classList.add('hidden');$(id).setAttribute('aria-hidden','true')}
function openAdd(){ $('batchForm').reset();$('batchId').value='';$('batchPhase').value='F1';$('batchF1Days').value=state.settings.defaultF1;$('extendDays').value=0;$('batchModalTitle').textContent='Nouveau batch';$('batchSubmit').textContent='Démarrer la F1';show('batchModal')}
function openF2(id){const b=state.batches.find(x=>x.id===id);if(!b)return;$('f2Form').reset();$('f2BatchId').value=id;$('f2Days').value=state.settings.defaultF2;$('f2Liters').value=b.liters??'';$('f2TeaGrams').value=b.teaGrams??'';$('f2SugarGrams').value=b.sugarGrams??'';$('f2Notes').value='';$('f2ExtendDays').value=0;$('f2ModalTitle').textContent=`F2 · ${b.name}`;show('f2Modal')}
function openEdit(id){const b=state.batches.find(x=>x.id===id);if(!b)return;const d=dataFor(b);$('editId').value=b.id;$('editPhase').value=b.phase;$('editName').value=b.name||'';$('editDays').value=d.days||1;$('editLiters').value=b.liters??'';$('editTeaGrams').value=b.teaGrams??'';$('editSugarGrams').value=b.sugarGrams??'';$('editFlavor').value=b.flavor||'';$('editNotes').value=b.phase==='F2'?(b.f2Notes||''):(b.f1Notes||'');$('editExtendDays').value=0;$('editFlavorWrap').style.display=b.phase==='F2'?'grid':'none';$('editModalTitle').textContent=`Modifier · ${b.name} · ${b.phase}`;show('editModal')}
$('addBtn').addEventListener('click',openAdd);$('refreshBtn').addEventListener('click',()=>loadData(false));document.querySelectorAll('.nav-btn').forEach(b=>b.addEventListener('click',()=>page(b.dataset.page)));['closeBatchModal','closeF2Modal','closeEditModal'].forEach(id=>$(id).addEventListener('click',()=>hide(id)));document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)hide(m.id)}));
$('batchForm').addEventListener('submit',async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;try{await api('createF1',{name:$('batchName').value.trim(),f1Days:Number($('batchF1Days').value),liters:Number($('batchLiters').value||0),teaGrams:Number($('batchTeaGrams').value||0),sugarGrams:Number($('batchSugarGrams').value||0),f1Notes:$('batchNotes').value.trim()});hide('batchModal');toast('Batch F1 démarré ✅');await loadData(true)}catch(err){toast(err.message)}finally{btn.disabled=false}});
$('f2Form').addEventListener('submit',async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;try{await api('startF2',{id:$('f2BatchId').value,f2Days:Number($('f2Days').value),liters:Number($('f2Liters').value),sugarGrams:Number($('f2SugarGrams').value||0),teaGrams:Number($('f2TeaGrams').value||0),flavor:$('f2Flavor').value.trim(),f2Notes:$('f2Notes').value.trim(),extendDays:Number($('f2ExtendDays').value||0)});hide('f2Modal');toast('F2 démarrée ✅');await loadData(true)}catch(err){toast(err.message)}finally{btn.disabled=false}});
$('editForm').addEventListener('submit',async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;try{await api('updateBatch',{id:$('editId').value,phase:$('editPhase').value,name:$('editName').value.trim(),days:Number($('editDays').value),liters:Number($('editLiters').value||0),teaGrams:Number($('editTeaGrams').value||0),sugarGrams:Number($('editSugarGrams').value||0),flavor:$('editFlavor').value.trim(),notes:$('editNotes').value.trim(),extendDays:Number($('editExtendDays').value||0)});hide('editModal');toast('Modifications enregistrées ✅');await loadData(true)}catch(err){toast(err.message)}finally{btn.disabled=false}});
$('settingsForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('saveSettings',{defaultF1:Number($('defaultF1').value),defaultF2:Number($('defaultF2').value)});state.settings.defaultF1=Number($('defaultF1').value);state.settings.defaultF2=Number($('defaultF2').value);toast('Settings enregistrés ✅')}catch(err){toast(err.message)}});
document.addEventListener('click',async e=>{const el=e.target.closest('[data-action]');if(!el)return;try{const a=el.dataset.action;if(a==='f2')openF2(el.dataset.id);else if(a==='edit')openEdit(el.dataset.id);else if(a==='rate'){await api('rate',{id:el.dataset.id,rating:Number(el.dataset.rating)});toast('Note enregistrée 👍');await loadData(true)}}catch(err){toast(err.message)}});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.deferredPrompt=e;$('installBtn').classList.remove('hidden')});$('installBtn').addEventListener('click',async()=>{if(!state.deferredPrompt)return;state.deferredPrompt.prompt();await state.deferredPrompt.userChoice;state.deferredPrompt=null;$('installBtn').classList.add('hidden')});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));setInterval(ticks,60000);loadData(false).catch(()=>{});
